# Generated by Django 6.0.2 on 2026-04-29 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_dailyhealthentry_sleep_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhealthentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dailyscore',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='energy_level',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='fruit_veg_servings',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='mood_level',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='protein_grams',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(350)]),
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='screen_time_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='steps',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AddField(
            model_name='dailyhealthentry',
            name='stress_level',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='dailyscore',
            name='model_version',
            field=models.CharField(default='rule_based_baseline', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyscore',
            name='predicted_improvements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailyscore',
            name='recommendation_source',
            field=models.CharField(choices=[('RULE_BASED', 'Rule-based'), ('ML_MODEL', 'Machine learning')], default='RULE_BASED', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_goal',
            field=models.CharField(choices=[('GENERAL', 'General health'), ('FITNESS', 'Improve fitness'), ('WEIGHT_LOSS', 'Weight loss'), ('MUSCLE_GAIN', 'Muscle gain'), ('WELLBEING', 'Improve wellbeing')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(230)]),
        ),
        migrations.AlterField(
            model_name='dailyhealthentry',
            name='calories_kcal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8000)]),
        ),
        migrations.AlterField(
            model_name='dailyhealthentry',
            name='exercise_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='dailyhealthentry',
            name='sleep_hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='dailyhealthentry',
            name='water_ml',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8000)]),
        ),
        migrations.AlterField(
            model_name='dailyscore',
            name='advice',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dailyscore',
            name='overall_score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyscore',
            name='subscores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
